package dev.kyuelin.accounting1.utils;

import java.util.HashMap;
import java.util.Map;

public class Constants {
    public static final Map<String, String> catMap = new HashMap<String, String>();
    static {
        catMap.put("Air Travel","Tickets");
        catMap.put("Alcohol & Bars","Food & Dining");
        catMap.put("Amusement","Entertainment");
        catMap.put("Auto & Transport","Parking/Toll");
        catMap.put("Auto Insurance","Auto");
        catMap.put("Auto Payment","Auto");
        catMap.put("Baby Supplies","Personal Supplies");
        catMap.put("Bills & Utilities","Transfer");
        catMap.put("Books","Books");
        catMap.put("Books & Supplies","Books");
        catMap.put("Business Services","Other");
        catMap.put("Cash & ATM","Cash");
        catMap.put("Charity","Cash");
        catMap.put("Check","Transfer");
        catMap.put("Clothing","Clothing");
        catMap.put("Coffee Shops","Food & Dining");
        catMap.put("Credit Card Payment", "Transfer");
        catMap.put("Doctor","Doctor/Dentist");
        catMap.put("Education","School Tuition/Camp");
        catMap.put("Electronics & Software","Other");
        catMap.put("Entertainment","Other");
        catMap.put("Eyecare","Doctor/Dentist");
        catMap.put("Fast Food","Food & Dining");
        catMap.put("Federal Tax","Federal Taxs");
        catMap.put("Food & Dining","Food & Dining");
        catMap.put("Furnishings","Furnishings/Appliances/Improvements");
        catMap.put("Gas & Fuel","Fuel");
        catMap.put("Gift","Other");
        catMap.put("Gifts & Donations","Other");
        catMap.put("Groceries","Groceries");
        catMap.put("Hobbies","Other");
        catMap.put("Home Improvement","Furnishings/Appliances/Improvements");
        catMap.put("Hotel","Lodging");
        catMap.put("Income","Wages & Tips");
        catMap.put("Interest Income","Interest Income");
        catMap.put("Internet","Internet");
        catMap.put("Kids","Other");
        catMap.put("Kids Activities","Other");
        catMap.put("Mobile Phone","Phone");
        catMap.put("Mortgage & Rent","Mortgage & Rent");
        catMap.put("Movies & DVDs","Movies/Theater/Music");
        catMap.put("Music","Movies/Theater/Music");
        catMap.put("Newspapers & Magazines","Books");
        catMap.put("Office Supplies","Other");
        catMap.put("Parking","Parking/Toll");
        catMap.put("Personal Care","Personal Supplies");
        catMap.put("Pharmacy","Medicine/Drugs");
        catMap.put("Printing","Other");
        catMap.put("Property Tax","State/Local Taxes");
        catMap.put("Public Transportation","Bus/Taxi/Train Fare");
        catMap.put("Rental Car & Taxi","Rental Car");
        catMap.put("Rental Income","Other - R");
        catMap.put("Restaurants","Food & Dining");
        catMap.put("Service & Parts","Repairs");
        catMap.put("Service Fee","Other");
        catMap.put("Shopping","Other");
        catMap.put("Sporting Goods","Sports");
        catMap.put("Sports","Sports");
        catMap.put("State Tax","State/Local Taxes");
        catMap.put("Toys","Toys/Games");
        catMap.put("Transfer","Transfer");
        catMap.put("Transfer for Cash Spending","Transfer");
        catMap.put("Tuition","School Tuition/Camp");
        catMap.put("Uncategorized","Uncategorized");
        catMap.put("Utilities","Gas/Oil");
    }

    public static final Map<String, String> segMap = new HashMap<String, String>();
    static {
        segMap.put("Air Travel","VACATION");
        segMap.put("Alcohol & Bars","DAILY LIVING");
        segMap.put("Amusement","VACATION");
        segMap.put("Auto & Transport","TRANSPORTATION");
        segMap.put("Auto Insurance","INSURANCE");
        segMap.put("Auto Payment","OBLIGATIONS");
        segMap.put("Baby Supplies","DAILY LIVING");
        segMap.put("Bills & Utilities","HOME EXPENSES");
        segMap.put("Books","ENTERTAINMENT");
        segMap.put("Books & Supplies","ENTERTAINMENT");
        segMap.put("Business Services","DAILY LIVING");
        segMap.put("Cash & ATM","DAILY LIVING");
        segMap.put("Charity","DAILY LIVING");
        segMap.put("Check","HOME EXPENSES");
        segMap.put("Clothing","DAILY LIVING");
        segMap.put("Coffee Shops","DAILY LIVING");
        segMap.put("Credit Card Payment", "HOME EXPENSES");
        segMap.put("Doctor","HEALTH");
        segMap.put("Education","CHILDREN");
        segMap.put("Electronics & Software","ENTERTAINMENT");
        segMap.put("Entertainment","ENTERTAINMENT");
        segMap.put("Eyecare","HEALTH");
        segMap.put("Fast Food","DAILY LIVING");
        segMap.put("Federal Tax","OBLIGATIONS");
        segMap.put("Food & Dining","DAILY LIVING");
        segMap.put("Fast Food","DAILY LIVING");
        segMap.put("Furnishings","HOME EXPENSES");
        segMap.put("Gas & Fuel","TRANSPORTATION");
        segMap.put("Gift","DAILY LIVING");
        segMap.put("Gifts & Donations","DAILY LIVING");
        segMap.put("Groceries","DAILY LIVING");
        segMap.put("Hobbies","ENTERTAINMENT");
        segMap.put("Home Improvement","HOME EXPENSES");
        segMap.put("Hotel","VACATION");
        segMap.put("Income","INCOME");
        segMap.put("Interest Income","INCOME");
        segMap.put("Internet","HOME EXPENSES");
        segMap.put("Kids","CHILDREN");
        segMap.put("Kids Activities","CHILDREN");
        segMap.put("Mobile Phone","HOME EXPENSES");
        segMap.put("Mortgage & Rent","HOME EXPENSES");
        segMap.put("Movies & DVDs","ENTERTAINMENT");
        segMap.put("Music","ENTERTAINMENT");
        segMap.put("Newspapers & Magazines","ENTERTAINMENT");
        segMap.put("Office Supplies","DAILY LIVING");
        segMap.put("Parking","TRANSPORTATION");
        segMap.put("Personal Care","DAILY LIVING");
        segMap.put("Pharmacy","HEALTH");
        segMap.put("Printing","DAILY LIVING");
        segMap.put("Property Tax","OBLIGATIONS");
        segMap.put("Public Transportation","TRANSPORTATION");
        segMap.put("Rental Car & Taxi","VACATION");
        segMap.put("Rental Income","INCOME");
        segMap.put("Restaurants","DAILY LIVING");
        segMap.put("Service & Parts","TRANSPORTATION");
        segMap.put("Service Fee","TRANSPORTATION");
        segMap.put("Shopping","DAILY LIVING");
        segMap.put("Sporting Goods","ENTERTAINMENT");
        segMap.put("Sports","ENTERTAINMENT");
        segMap.put("State Tax","OBLIGATIONS");
        segMap.put("Toys","CHILDREN");
        segMap.put("Transfer","HOME EXPENSES");
        segMap.put("Transfer for Cash Spending","HOME EXPENSES");
        segMap.put("Tuition","CHILDREN");
        segMap.put("Uncategorized","HOME EXPENSES");
        segMap.put("Utilities","HOME EXPENSES");
        segMap.put("Credit Card Payment","HOME EXPENSES");
    }
}
